// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbdklgroyyqcpuggszxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZGtsZ3JveXlxY3B1Z2dzenhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzE0OTEsImV4cCI6MjA2ODAwNzQ5MX0.T_UVOv6UYWLX644I9tamNJ57WKLI-WtYazpLJ_SInWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});